import Head from "next/head";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import requests from "@/utils/requests";
import Result from "@/components/Result";

export default function Home({results}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Result results={results}/>
    </>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  console.log(genre)

  const request = await fetch(`https://api.themoviedb.org/3${
    requests[genre]?.url || requests.fetchTrending.url}`
  ).then((res) => res.json());

  return{
    props: {
      results: request.results,
    }
  }
}
